spring.application.name=gluetun-qbittorrent-portforward

# Logging
logging.file.name=/home/tezzad/log/port-protonvpn.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %msg%n
logging.level.root=ERROR
logging.level.com.tezzad=INFO

# App Configuration
app.gluetun.container-name=gluetun
app.gluetun.base-url=http://10.25.25.32:8000
app.qbittorrent.container-name=qbittorrent
app.qbittorrent.base-url=http://10.25.25.32:8081

# Scheduling Frequency (in milliseconds)
# 60000 = 1 minute, 300000 = 5 minutes
app.sync.frequency-ms=300000